language: java
jdk: open jdk8

script: 
  - echo "Hola travis"
  - mvn package
  - chmod 400 acceso_instancia.pem
  - ssh-keyscan -H 3.20.238.233 >> ~/.ssh/known_hosts
  - ssh-keyscan -H ec2-3-20-238-233.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
   #- scp -i pruebaAWS.pem ubuntu@3.136.12.181 "rm -rf /var/lib/tomcat8/webapps/Netflix*
  - scp -i acceso_instancia.pem target/Netflix-1.0-SNAPSHOT.war ubuntu@3.20.238.233:/var/lib/tomcat8/webapps/Netflix.war
