language: java
jdk: open jdk8

script: 
  - echo "Hola travis"
  - mvn package
  - ssh-keyscan -H 3.20.238.233 >> ~/.ssh/known_hosts
  - ssh-keyscan -H ec2-3-20-238-233.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
  - scp -i .\acceso_instancia.pem target/Netflix-1.0 SNAPSHO.war ubuntu@3.20.238.233:/tmp